### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by jarib** [fantasticfears/ffi-icu#31]
I don't really use ffi-icu or do much Ruby at the moment. Is anyone interested in taking over this project?

@cbandy 
@marek-veber 
@brianphillips 
@fantasticfears 
@cfis

**Comment by fantasticfears** [comment]
I am going to use spoof checker in the future. Then I am really interested in being a maintainer.

**Comment by cfis** [comment]
Seems fairly mature to me so that's good...don't really want to be the maintainer, but can pitch in ever so often if needed.

**Comment by jarib** [comment]
@fantasticfears Still interested? I can transfer ownership to your account and add you to the gem on rubygems.org

Maybe @ccutrer is interested as well.

**Comment by fantasticfears** [comment]
Yes. I am still interested. Thanks for your work!

BTW: Progress report. I am starting to investigate some internal ruby string implementation. I could nail my change for next few days.

**Comment by jarib** [comment]
Great! You're now an owner on rubygems.org

I can't transfer ownership unless you remove your fork though:

![image](https://cloud.githubusercontent.com/assets/572/12689941/3abf674c-c6e0-11e5-9a43-6b25c0ecc901.png)

**Comment by fantasticfears** [comment]
Deleted

**Comment by cfis** [comment]
Should we close this ticket?
